# Generated by Django 5.0.4 on 2024-04-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, verbose_name='URL')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('artist', models.CharField(max_length=50, verbose_name='アーティスト名')),
            ],
        ),
    ]
