# Generated by Django 4.2.11 on 2024-04-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shelf_Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=255)),
                ("music_title", models.CharField(max_length=255)),
                ("music_picture", models.ImageField(upload_to="")),
                ("posted_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
