# Generated by Django 4.2.11 on 2024-04-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music_shelf", "0002_shelf_post_music_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("document", models.FileField(upload_to="documents/")),
                ("music_url", models.URLField(null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
